function numberFromEnv(name, fallback) {
  const value = Number(process.env[name]);
  return Number.isFinite(value) ? value : fallback;
}

function booleanFromEnv(name, fallback = false) {
  const value = process.env[name];
  if (value === undefined) return fallback;
  return ["1", "true", "yes", "on"].includes(String(value).toLowerCase());
}

function normalizeHost(host) {
  const raw = String(host || "deliveroojs.azurewebsites.net").trim();
  if (/^https?:\/\//i.test(raw)) return raw;
  return `http://${raw}`;
}

const fastCloudMode = booleanFromEnv("FAST_CLOUD_MODE", false);

export const CONFIG = {
  host: normalizeHost(process.env.HOST),
  token: process.env.TOKEN ?? "",
  agentName: process.env.AGENT_NAME ?? "PlannerAgent",
  logLevel: process.env.LOG_LEVEL ?? "info",
  actionDelayMs: numberFromEnv("ACTION_DELAY_MS", 100),
  fastCloudMode,
  telemetryEnabled: booleanFromEnv("TELEMETRY_ENABLED", false),
  telemetryFile: process.env.TELEMETRY_FILE ?? "telemetry.jsonl",
  telemetry: {
    enabled: booleanFromEnv("TELEMETRY_ENABLED", false),
    file: process.env.TELEMETRY_FILE ?? "telemetry.jsonl"
  },
  planner: {
    fastCloudMode,
    meanPackageValue: 10,
    packageVariance: 0,
    decayRate: 1,
    generationMeanTime: null,
    generationProbability: null,
    maxPackages: Infinity,
    kSmoothMax: 0.25,
    kWin: 1,
    rhoGeneration: 0.1,
    moveWeight: 1,
    betaCarry: 0.5,
    periodicReplanTicks: fastCloudMode ? 30 : 20,
    eventCoalesceMs: numberFromEnv("EVENT_COALESCE_MS", fastCloudMode ? 50 : 0),
    minReplanIntervalMs: numberFromEnv("MIN_REPLAN_INTERVAL_MS", fastCloudMode ? 80 : 0),
    minScoutReplanIntervalMs: numberFromEnv("MIN_SCOUT_REPLAN_INTERVAL_MS", fastCloudMode ? 150 : 0),
    timeTickMs: 1000,
    minParcelConfidence: 0.3,
    enemySafetyMargin: 0,
    beliefDecayRate: 0.08,
    sensingRange: 5,
    scoutCooldownTicks: 8,
    sameScoutTargetPenalty: 15,
    recentScoutPenalty: 10,
    scoutDistanceWeight: 0.8,
    scoutRedDistanceWeight: 0.1,
    scoutFutureWeight: 2,
    scoutCongestionDistance: 2,
    scoutEnemyDistance: 2,
    scoutCongestionPenalty: 10,
    noveltyBonus: 5,
    emptyGreenFutureWeight: 0,
    maxStalenessValue: 30,
    greenInfoMultiplier: 4,
    redInfoMultiplier: 0.2,
    infoValueWeight: 1,
    clusterPickupRadius: 3,
    clusterPickupBonusWeight: 0.6,
    minClusterPackageValue: 3,
    greenClusterDistance: 2,
    clusterSizeWeight: 3,
    explorationDebtThreshold: 25,
    explorationDebtBonus: 30,
    localCandidateRadius: 4,
    localCandidateLimit: fastCloudMode ? 3 : 4,
    clusterExpansionRadius: 3,
    clusterExpansionLimit: fastCloudMode ? 3 : 6,
    maxCandidateGreens: fastCloudMode ? 8 : 16,
    maxVisiblePackageCandidates: fastCloudMode ? 12 : 24,
    maxBeliefPackageCandidates: fastCloudMode ? 16 : 32,
    maxGreenCandidates: fastCloudMode ? 12 : 32,
    maxOraclePoints: fastCloudMode ? 20 : 64,
    localExploreReversePenalty: 20,
    localExploreInfoWeight: 1,
    denseGreenThreshold: 0.65,
    denseGreenMinGreens: 100,
    denseScoutRadius: 6,
    denseScoutMaxWaypoints: fastCloudMode ? 6 : 12,
    denseScoutMinDistanceFromLastDelivery: 2,
    greenExposureDepth: fastCloudMode ? 4 : 6,
    greenExposureBeamWidth: fastCloudMode ? 8 : 16,
    greenExposureMaxExpanded: fastCloudMode ? 24 : 48,
    greenExposureMinPlanLength: 3,
    greenExposureStaleWeight: 2,
    greenExposureNewTileWeight: 1,
    greenExposureGreenWeight: 1,
    greenExposureDistanceWeight: 1,
    greenExposureBacktrackPenalty: 5,
    minGreenExposureScore: 0,
    positionRevisitPenalty: 4,
    edgeRevisitPenalty: 6,
    sameTargetPenalty: 30,
    sameSectorPenalty: 20,
    failedScoutTargetPenalty: 50,
    failedScoutTargetCooldownTicks: 40,
    edgeCooldownTicks: 20,
    positionCooldownTicks: 20,
    coverageSectorSize: 5,
    returnToRedWeight: 0.5,
    trapPenalty: 10000,
    planningBudgetMs: fastCloudMode ? 25 : 30,
    hardPlanningBudgetMs: fastCloudMode ? 60 : 100,
    mazeObstacleDensityThreshold: 0.25,
    enableEdgeTemporaryBlocks: true,
    temporaryEdgeBlockTtlTicks: 2,
    maxRepeatedBlockedMovesBeforeReplan: 2,
    opportunisticMaxDistance: 3,
    opportunisticPathRadius: 2,
    opportunisticCheckIntervalTicks: 2,
    opportunisticMinGain: 5,
    enableImmediateNearbyPickup: true,
    nearbyPickupMaxDistance: 3,
    nearbyPickupMaxCandidates: 8,
    nearbyPickupMinEstimatedValue: 1,
    opportunisticMaxExtraCost: 3,
    opportunisticMinValue: 5,
    opportunisticCongestionPenalty: 8,
    targetCongestionPenalty: 0,
    deliveryUrgencyWeight: 0,
    maxPlanningTimeMs: fastCloudMode ? 60 : 30,
    beamWidth: fastCloudMode ? 12 : undefined,
    topK: fastCloudMode ? 8 : undefined,
    maxPickupsBeforeDelivery: fastCloudMode ? 3 : undefined,
    candidateDiagnosticsLimit: fastCloudMode ? 5 : 10,
    ignoredVisiblePackagesLimit: fastCloudMode ? 5 : 10,
    diagnosticsLimit: fastCloudMode ? 5 : 10,
    compactLogging: fastCloudMode
  }
};
